version: "1.0"
buildspecs:
  shared_qos_haswell_hostname:
    description: run hostname through shared qos on Haswell
    type: script
    executor: cori.slurm.haswell_shared
    sbatch:
      - "-t 5"
      - "-N 1"
    tags: ["queues","jobs"]
    run: hostname

