version: "1.0"
buildspecs:
  e4s_adios2:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run adios2 test from E4S Testsuite
    tags: [e4s]
    sbatch: ["-t 30", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      source ./setup.sh
      sh test-all.sh --color-off validation_tests/adios2 --print-logs --settings settings.cori.sh

  e4s_bolt:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run bolt test from E4S Testsuite
    tags: [e4s]
    sbatch: ["-t 30", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      source ./setup.sh
      sh test-all.sh --color-off validation_tests/bolt --print-logs --settings settings.cori.sh


  e4s_hdf5:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run hdf5 test from E4S Testsuite. This test is expected to fail
    tags: [e4s]
    sbatch: ["-t 30", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      source ./setup.sh
      sh test-all.sh --color-off validation_tests/hdf5 --print-logs --settings settings.cori.sh
    status:
      state: FAIL

  e4s_hypre:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run hypre test from E4S Testsuite
    tags: [e4s]
    sbatch: ["-t 30", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      source ./setup.sh
      sh test-all.sh --color-off validation_tests/hypre --print-logs --settings settings.cori.sh

  e4s_strumpack:
    type: script
    executor: cori.slurm.haswell_debug
    description: Run STRUMPACK test from E4S Testsuite
    tags: [e4s]
    sbatch: ["-t 30:00", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      source ./setup.sh
      sh test-all.sh --color-off validation_tests/strumpack --print-logs --settings settings.cori.sh

  e4s_tau.pdt.papi:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run NPB3.1 test from E4S Testsuite to test TAU, PDT and PAPI
    tags: [e4s]
    sbatch: ["-t 30", "-N 1"]
    run: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      sh test-all.sh --color-off validation_tests/NPB3.1 --print-logs --settings settings.cori.sh

maintainers:
  - "@shahzebsiddiqui"
  - "@wspear"
