buildspecs:
  hello_world_openmp:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: Hello World OpenMP example on login node with all PrgEnv modules
    tags: [compile,openmp]
    env:
      OMP_NUM_THREADS: "4"
    compilers:
      name: ["^(gcc|cce)"]
      default:
        gcc:
          cc: gcc
          cflags: -fopenmp 
        cray:
          cflags: -craype-verbose -fopenmp 
    run: |
      $BUILDTEST_CC $BUILDTEST_CFLAGS -o hello src/hello.c
      ./hello

