buildspecs:
  hello_world_openmp:
    type: compiler
    executor: perlmutter.local.bash
    source: src/hello.c
    description: Hello World OpenMP example on login node with all PrgEnv modules
    tags: [compile,openmp]
    compilers:
      name: ["^(gcc|cce)"]
      default:
        all:
          env:
            OMP_NUM_THREADS: "4"
        gcc:
          cflags: -fopenmp
        cray:
          cflags: -h omp
