buildspecs:
  openmp_scale:
    type: compiler
    executor: '(perlmutter|muller).local.bash'
    source: src/hello.c
    description: Hello World OpenMP scaling example with processor count
    tags: [openmp]
    compilers:
      name: ["^(gcc)"]
      default:
        gcc:
          env:
            OMP_NUM_THREADS: "$BUILDTEST_NUMPROCS"
          cflags: -fopenmp
          sbatch: ['-t 5', '-C cpu']  
