buildspecs:
  openmp_scale:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: Hello World OpenMP scaling example with processor count
    tags: [openmp]
    compilers:
      name: ["^(gcc)"]
      default:
        gcc:
          env:
            OMP_NUM_THREADS: "$BUILDTEST_NUMPROCS"
          cflags: -fopenmp
    run: |
      $BUILDTEST_CC $BUILDTEST_CFLAGS -o hello src/hello.c
      ./hello
