version: "1.0"
buildspecs:
  reduction:
    type: compiler
    executor: cori.local.bash
    source: src/reduction.c
    description: OpenMP reduction example using gcc, intel, PrgEnv-cray compiler
    tags: [openmp]
    compilers:
      name: ["^(gcc|intel|PrgEnv-cray)"]
      default:
        all:
          env:
            OMP_NUM_THREADS: 4
        gcc:
          cflags: -fopenmp
        intel:
          cflags: -qopenmp
        cray:
          cflags: -h omp      
