buildspecs:
  reduction:
    type: compiler
    executor: perlmutter.local.bash
    source: src/reduction.c
    description: OpenMP reduction example using gcc and cray compiler
    tags: [openmp]
    compilers:
      name: ["^(gcc|cce)"]
      default:
        all:
          env:
            OMP_NUM_THREADS: 4
        gcc:
          cflags: -fopenmp
        cray:
          cflags: -h omp      
