buildspecs:
  reduction:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: OpenMP reduction example using gcc and cray compiler
    tags: [openmp]
    env:
      OMP_NUM_THREADS: 4
    compilers:
      name: ["^(gcc|cce)"]
      default:  
        gcc:
          cc: gcc
          cflags: -fopenmp
        cray:
          cflags: -fopenmp      
    run: |
      $BUILDTEST_CC $BUILDTEST_CFLAGS -o reduction src/reduction.c
      ./reduction
