package:
- aml
- arborx
- bolt
- caliper
- fortrilinos
- ginkgo
- hpctoolkit
- kokkos
- legion
- mfem
- omega-h
- papyrus
- parsec
- py-h5py
- py-libensemble
- py-petsc4py
- py-warpx
- qthreads
- slate
- slepc
- superlu
- tau
