buildspecs:
  srun_gpu_binding:
    type: script
    executor: '(perlmutter|muller).slurm.regular'
    description: GPU binding example with srun
    sbatch: ["-N 1", "-C gpu", "-G 4", "-t 5", "--ntasks-per-node=8", "--cpus-per-task=2", "-A m3503_g"]
    tags: [gpu]
    run: |
      ml PrgEnv-nvidia
      ml cudatoolkit
      lscpu | grep NUMA
      echo -e "\n"
      make
      srun -n8 --cpu-bind=cores --gpu-bind=closest ./vec_add
      srun -n8 --cpu-bind=cores ./vec_add


