version: "1.0"
buildspecs:
  e4s_kokkos:
    type: script
    executor: cori.slurm.e4s
    description: Run kokkos test from E4S Testsuite
    tags: [e4s]
    run: $SCRATCH/testsuite/test-all.sh $SCRATCH/testsuite/validation_tests/kokkos --settings $SCRATCH/testsuite/settings.cori.sh

  e4s_kokkoskernels:
    type: script
    executor: cori.slurm.e4s
    description: Run kokkos kernels test from E4S Testsuite
    tags: [e4s]
    run: $SCRATCH/testsuite/test-all.sh $SCRATCH/testsuite/validation_tests/kokkos-kernels --settings $SCRATCH/testsuite/settings.cori.sh
