version: "1.0"
buildspecs:
  e4s_adios2:
    type: script
    executor: cori.slurm.e4s
    description: Run adios2 test from E4S Testsuite
    tags: [e4s]
    run: $SCRATCH/testsuite/test-all.sh $SCRATCH/testsuite/validation_tests/adios2 --settings $SCRATCH/testsuite/settings.cori.sh
