buildspecs:
  e4s_testsuite_e4s_22.02_intel:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run E4S Testsuite for e4s/22.02, intel stack
    tags: [e4s]
    sbatch: ["-t 40", "-N 1"]
    run: |
      module swap PrgEnv-gnu PrgEnv-intel
      module load e4s/22.02
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      export TESTSUITE_VARIANT="%intel"
      sh test-all.sh --color-off --print-logs --settings settings.cori.sh  --test-only "adios2 arborx caliper conduit faodel gasnet ginkgo hypre legion libquo llvm netcdf-c parallel-netcdf parsec petsc qthreads strumpack sz zfp"
maintainers:
  - shahzebsiddiqui
  - wspear
