buildspecs:
  hpctoolkit_cuda_pc:
    executor: '(perlmutter|muller).slurm.regular'
    type: script
    description: "HPCToolkit vector add CUDA test with PC sampling"
    tags: ["e4s"]
    sbatch: ["-A m3503", "-C gpu", "-N 1", "-G 1", "-t 00:05:00"]
    run: |
      module load e4s/22.11 || exit $?
      module load PrgEnv-nvidia || exit $?
      spack env activate -V cuda || exit $?
      spack load hpctoolkit+cuda || exit $?

      rm -f cuda_vecadd
      nvcc -o cuda_vecadd -g -arch=sm_80 cuda_vecadd.cu || exit $?

      out=hpctoolkit-vecadd-pc
      n=1048576

      srun --ntasks-per-node=1 dcgmi profile --pause || exit $?
      rm -rf $out.m
      srun -n 1 -c 1 -G 1 hpcrun -e gpu=nvidia,pc -o $out.m ./cuda_vecadd $n || exit $?
      srun --ntasks-per-node=1 dcgmi profile --resume || exit $?

      grep 'accelerator trace records:' $out.m/*.log | grep --only-matching 'processed: [[:digit:]]\+' | awk '{print $2}' > numrecords.txt

      srun -n 1 -c 64 -G 0 hpcstruct --gpucfg yes $out.m || exit $?
      rm -rf $out.d
      srun -n 1 -c 64 -G 0 hpcprof -o $out.d $out.m || exit $?

    metrics:
      accelerator_samples:
        type: int
        file_regex:
          file: "numrecords.txt"
          exp: '\d+
    status:
      mode: "all"
      returncode: 0
      file_count:
      - dir: "hpctoolkit-vecadd.m"
        ext: ".hpcrun"
        depth: 1
        count: 1
      - dir: "hpctoolkit-vecadd.m/structs"
        filepattern: '\.gpubin-gpucfg-yes\.hpcstruct$'
        depth: 1
        count: 1
      assert_ge:
      - name: accelerator_samples
        ref: 100
      exists:
      - "hpctoolkit-vecadd.d/meta.db"
      - "hpctoolkit-vecadd.d/profile.db"
      - "hpctoolkit-vecadd.d/cct.db"

maintainers:
  - wyphan
  - blue42u
