buildspecs:
  spack_test_hpctoolkit_e4s_21.11:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test hpctoolkit build with for e4s/22.05 stack on Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['hpctoolkit']
        results:
          option: '-l'
          specs: ['hpctoolkit']


