buildspecs:
  e4s_testsuite_e4s_22.02_gnu:
    type: script
    executor: cori.slurm.haswell_premium
    description: Run E4S Testsuite for e4s/22.02, gnu stack
    tags: [e4s]
    sbatch: ["-t 40", "-N 1"]
    run: |
      module swap PrgEnv-intel PrgEnv-gnu
      #module swap intel intel/19.1.3.304
      module load e4s/22.02
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite
      export TESTSUITE_VARIANT="%gcc"
      #sh test-all.sh --color-off --print-logs --settings settings.cori.sh  --run-only "adios2 aml arborx bolt caliper conduit dyninst faodel gasnet ginkgo legion llvm netcdf-c parallel-netcdf parsec petsc qthreads strumpack sz vtk-m zfp"
      sh test-all.sh --color-off --print-logs --settings settings.cori.sh  --test-only "adios2 aml arborx bolt caliper conduit dyninst faodel gasnet ginkgo legion llvm netcdf-c parallel-netcdf parsec petsc qthreads sz vtk-m zfp"
maintainers:
  - shahzebsiddiqui
  - wspear
