buildspecs:
  install_osu_benchmark:
    type: script
    executor: perlmutter.local.bash
    description: Install OSU benchmark
    run: |
      module load PrgEnv-gnu
      wget https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.9.tar.gz
      tar xf osu-micro-benchmarks-5.9.tar.gz
      cd osu-micro-benchmarks-5.9
      ./configure CC=$(which cc) CXX=$(which CC) --prefix=$HOME/benchmarks/osu
      make
      make install
  osu_bandwidth_test:
    type: script
    needs: [install_osu_benchmark]
    executor: perlmutter.slurm.regular
    sbatch: ["-A nstaff_g", "-t 5", "-n 2", "-N 2", "-C gpu"]
    description: Run osu bandwidth test (osu_bw, osu_bibw) on 2 nodes with 2 MPI processes
    run: |
      module load PrgEnv-gnu
      srun -n 2 $HOME/benchmarks/osu/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bibw
      srun -n 2 $HOME/benchmarks/osu/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw

