
buildspecs: 
  spack_test_gasnet_e4s_21.05:
    type: spack
    executor: cori.local.sh
    description: "Test gasnet@2021.3.0%intel with e4s/21.05 via spack test"
    tags: e4s
    pre_cmds: module load e4s/21.05
    spack:
      root: /global/common/software/spackecp/e4s-21.05/spack/
      verify_spack: false
      test: 
        run:
          specs: ['gasnet@2021.3.0%intel']
        results:
          option: '-l'
          specs: ['gasnet@2021.3.0%intel']
maintainers:
  - "shahzebsiddiqui"
  - "PHHargrove"
  - "bonachea"
