buildspecs: 
  spack_test_gasnet_e4s_22.02:
    type: spack
    executor: cori.local.bash
    description: "Test gasnet@2022.9.0 for e4s/22.02 stack"
    tags: e4s
    pre_cmds: module load e4s/22.02
    spack:
       root: /global/common/software/spackecp/cori/e4s-22.02/spack
       verify_spack: false
       test:
         run:
           specs: ['gasnet@2021.9.0%intel', 'gasnet@2021.9.0%gcc']
         results:
           option: '-l'
           specs: ['gasnet@2021.3.0%intel', 'gasnet@2021.9.0%gcc']
maintainers:
  - "shahzebsiddiqui"
  - "PHHargrove"
  - "bonachea"
