buildspecs:
  superlu-dist_e4s_testsuite_21.11:
    type: script
    executor: '(perlmutter|muller).slurm.regular'
    description: Run E4S Testsuite superlu-dist test for e4s/21.11-tcl stack
    tags: [e4s]
    skip: true
    summary: "The spack-test run by this buildspec fails up to and including the release of e4s 22.05."
    sbatch: ["-t 30", "-N 1", "-G 1", "-A m3503_g", "-C gpu"]
    run: |
      module load e4s/21.11
      spack env activate -V e4s
      spack load cmake
      git clone https://github.com/E4S-Project/testsuite
      cd testsuite

      sh test-all.sh --color-off validation_tests/superlu-dist --print-logs --settings settings.cray.sh
maintainers:
  - shahzebsiddiqui
  - wspear
