version: "1.0"
buildspecs:
  bash_alias:
    type: cori.script
    shebang: "#!/bin/bash -l"
    description: "Check predefined alias set in /etc/profile.d script"
    tags: [daily, system]
    executor: local.bash
    run: |
      shopt -s expand_aliases
      alias
      alias o
      alias ..
      alias ...
      alias rd
      alias egrep
      alias grep
      alias md
      aliash rehash
      alias beep
      alias you
      alias unmount

