version: "1.0"
buildspecs:
  vecadd_hpcsdk_gnu:
    type: compiler
    description: Vector Addition example with hpcsdk (pgi) compiler
    executor: slurm.gpu
    sbatch: ["-G 1", "-t 5", "-N 1"]
    tags: ["gpu", "openacc"]
    module:
      load: [hpcsdk, cuda]
    source: src/vecAdd.c
    compilers:
      name: []
      cc: nvc
      source: src/vecAdd.c
      cflags: -acc
      ldflags: -lm
    run:
      launcher: srun
maintainers:
  - "@shahzebsiddiqui"
