buildspecs:
  vecadd_hpcsdk_gnu:
    type: script
    description: Vector Addition example with nvhpc compiler
    executor: '(perlmutter|muller).slurm.debug'
    tags: ["gpu", "openacc"]
    sbatch: ["-G 1", "-t 5", "-N 1", "-C gpu", "-A m3503_g"]
    compilers:
      name: ['nvhpc']
      default:
        nvhpc:
          cflags: -acc
          ldflags: -lm
    run: |
      $BUILDTEST_CC $BUILDTEST_CFLAGS -o vecadd src/vecAdd.c $BUILDTEST_LDFLAGS
      srun ./vecadd
maintainers:
  - "shahzebsiddiqui"
