buildspecs:
  spack_e4s_directory_checks:
    type: script
    description: Check for production directory paths for spack e4s stack
    executor: '(perlmutter|muller).local.bash'
    tags: [e4s,system]
    run: |
      ls -ld /global/common/software/spackecp/perlmutter/e4s-{22.11,23.05,23.08}/default/spack
      ls -l /global/common/software/spackecp/perlmutter/spack_settings/{compilers.yaml,packages.yaml}
  e4s_spack_settings:
    type: script
    description: Check spack site settings exist for all E4S stacks
    executor: '(perlmutter|muller).local.bash'
    tags: [e4s,system]
    run: | 
      ls /global/common/software/spackecp/perlmutter/e4s-{22.11,23.05,23.08}/default/spack/etc/spack/{config,mirrors,modules}.yaml

  buildcache_directory_check:
    type: script
    description: Check for directory existence for spack buildcache directory
    executor: '(perlmutter|muller).local.bash'
    tags: [e4s,system]  
    run: ls -ld /global/common/software/spackecp/mirrors/perlmutter-e4s-{22.11,23.05,23.08}/build_cache
    status:
      is_dir:
        - /global/common/software/spackecp/mirrors/perlmutter-e4s-22.11/build_cache
        - /global/common/software/spackecp/mirrors/perlmutter-e4s-23.05/build_cache
        - /global/common/software/spackecp/mirrors/perlmutter-e4s-23.08/build_cache
maintainers:
  - shahzebsiddiqui


