buildspecs:
  amrex_single_vortex:
    executor: perlmutter.slurm.regular
    type: script
    description: "AmrLevel SingleVortex Build and Run"
    tags: ["e4s"]
    sbatch:
      - "-N 1"
      - "-t 00:05:00"
      - "-C gpu"
      # Note: This test doesn't use GPUs.
    run: |
      module load e4s/21.11-tcl
      
      # Use the PrgEnv-gnu to avoid issues with NVHPC and Fortran
      module load PrgEnv-gnu

      spack load cmake
      spack load amrex

      # Store AMReX install location
      export AMR_DIR=$(spack location -i amrex)

      cd test/Exec
      mkdir build
      cd build

      cmake .. \
      -DAMReX_FORTRAN=ON \
      -DAMReX_FORTRAN_INTERFACES=ON \
      -DAMReX_DIR=${AMR_DIR}/lib/cmake/AMReX \
      -DAMReX_SPACEDIM=3

      cmake --build . -j4
      srun -n 4 ./SingleVortex ../inputs max_step=1

    status:
      regex:
        stream: stdout
        exp: "finalized"
maintainers:
  - epalmer
