buildspecs:
  e4s_21.11_dev_workflow:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: E4S/21.11 Developer Workflow Check
    tags: [e4s]
    summary: |
      This workflow will check the developer workflow for Perlmutter outlined in https://docs.nersc.gov/applications/e4s/perlmutter/21.11/
    run: |
      module load e4s/21.11-tcl
      source $SPACK_ROOT/bin/spack-setup.sh
      despactivate
      rm -rf $HOME/e4s-21.11-spack-demo
      ls -l
      spack env create -d $HOME/e4s-21.11-spack-demo
      spack env activate -d $HOME/e4s-21.11-spack-demo
      spack install m4
      spack install papi
      spack find
      spack location -i papi
      module use $HOME/spack-workspace/perlmutter/modules/tcl/cray-sles15-zen3
      ml -t av papi
maintainers:
 - "@shahzebsiddiqui"
