version: "1.0"
buildspecs:
  sgemm_intel:
    executor: local.bash
    type: compiler
    description: sgemm test with intel compilers
    tags: [mkl]
    source: src/mkl_sgemm.c
    compilers:
      name: [^(intel)]
      default:
        intel:
          cflag: -mkl



