buildspecs:
  hello_world_serial:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: hello world program in C compiled with gnu, nvhpc and cray compiler
    tags: [compile]
    compilers:
      name: ["^(gcc|nvhpc|cce)"]
      default:
        gcc:
          cc: gcc
          fc: gfortran
          cxx: g++  
        cray:
          cflags: -craype-verbose -O2
          fflags: -craype-verbose -O2
          cxxflags: -craype-verbose -O2
        nvhpc:
          cc: nvc
          fc: nvfortran  
          cxx: nvcc

    run: |
      $BUILDTEST_CC $BUILDTEST_CFLAGS -o hello_c src/hello.c
      $BUILDTEST_FC $BUILDTEST_FFLAGS -o hello_f src/hello.f90
      $BUILDTEST_CXX $BUILDTEST_CXXFLAGS -o hello_cpp src/hello.cpp
      ./hello_c
      ./hello_f
      ./hello_cpp
maintainers:
  - "shahzebsiddiqui"
