version: "1.0"
buildspecs:
  hello_fortran:
    type: compiler
    executor: local.bash
    description: hello world program in Fortran compiled with gnu compiler
    tags: [compile]
    source: src/hello.f90
    compilers:
      name: ["^(gcc)"]
      default:
        gcc:
          fflags: -O1


maintainers:
  - "Shahzeb Siddiqui <@shahzebmsiddiqui>"
