# https://gitlab.nersc.gov/nersc/consulting/reframe-at-nersc/reframe-nersc-tests/-/blob/main/esslurm/check_admin_comment_esslurm/check_admin_comment_esslurm.py
version: "1.0"
buildspecs:
  check_admin_comment_esslurm:
    type: script
    description: Check if a job has an admin comment after running for esslurm
    tags: [esslurm, checkout, reframe]
    executor: cori.slurm.bigmem
    batch:
      nodecount: "1"
      timelimit: "5"
    run: |
      module load esslurm
      ./admin_comment.sh
    status:
      regex:
        stream: stdout
        exp: "Admin comment found"
