buildspecs:
  check_admin_comment_esslurm:
    type: script
    description: Check if a job has an admin comment after running for esslurm
    tags: [slurm]
    executor: cori.slurm.bigmem
    sbatch: ["-N 1", "-t 5"]
    run: |
      module load esslurm
      ./admin_comment.sh
    status:
      regex:
        stream: stdout
        exp: "Admin comment found"
