version: "1.0"
buildspecs:
  likwid_topology_knl:
    type: script
    executor: slurm.knl_debug
    description: Show thread, numa and cahce topology on Haswell via likwid-topology
    tags: [tools]
    batch:
      nodecount: "1"
      timelimit: "5"
    run: |
      module load likwid
      likwid-topology -c
maintainers:
  - "Shahzeb Siddiqui @shahzebsiddiqui"
