buildspecs:
  likwid_topology_knl:
    type: script
    executor: cori.slurm.knl_debug
    description: Show thread, numa and cahce topology on Haswell via likwid-topology
    tags: [tools]
    sbatch: ["-N 1", "-t 5"]
    run: |
      module load likwid
      likwid-topology -c
maintainers:
  - "shahzebsiddiqui"
