
buildspecs:
  likwid_pin_cores:
    type: compiler
    executor: cori.slurm.knl_debug
    description: Run code using likwid-perfctr and acquire performance counter for MEM group  
    tags: [tools]
    source: xthi.c
    compilers:
      name: [^(intel/19.1.2.254)$]
      default:
        all:
          sbatch: ["-N 1", "-t 5", "-C knl,quad,cache", "--perf=likwid"]
          run: srun -n 1 likwid-perfctr -C 0,8,16,24 -g MEM $_EXEC
        intel:
          cflags: -qopenmp
          env:
            OMP_NUM_THREADS: 4
      config:
        intel/19.1.2.254:
          module:
            load: [likwid]
                
maintainers:
  - "shahzebsiddiqui"
