version: "1.0"
buildspecs:
  e4s_hypre:
    type: script
    executor: cori.slurm.e4s
    description: Run hypre test from E4S Testsuite
    tags: [e4s]
    run: $SCRATCH/testsuite/test-all.sh $SCRATCH/testsuite/validation_tests/hypre --settings $SCRATCH/testsuite/settings.cori.sh
