buildspecs:
  hybrid_mpi_hello_fortran_perlmutter:
    type: script
    executor: '(perlmutter|muller).slurm.debug'
    description: Hybrid MPI+OpenMP Hello World in Fortran on Perlmutter
    tags: [mpi, compile]
    sbatch: ["-N 1", "-n 8", "-t 20:00", "-A m3503", "-C cpu"]
    compilers:
      name: ["gcc/11.2.0"]
      default:
        gcc:
          fc: ftn
          env:
            OMP_NUM_THREADS: 8
            OMP_PROC_BIND: spread
            OMP_PLACES: threads
            OMP_DISPLAY_AFFINITY: true
            OMP_AFFINITY_FORMAT: '"host=%H, pid=%P, thread_num=%n, thread affinity=%A"'
    run: |
      $BUILDTEST_FC -openmp -o hybrid_hello src/hybrid-hello.f90
      srun -n 8 --cpu-bind=cores $_EXEC
maintainers:
  - shahzebsiddiqui  
