buildspecs:
  hybrid_mpi_hello_fortran_cori:
    type: compiler
    executor: cori.slurm.knl_debug
    description: Hybrid MPI+OpenMP Hello World in Fortran on Cori
    tags: [mpi, compile]
    source: src/hybrid-hello.f90
    compilers:
      name: ["^(intel/19.0.3.199)$", "^(intel/19.1.2.254)$"]
      default:
        intel:
          fc: mpiifort
          fflags: -qopenmp
          sbatch: ["-N 1", "-n 8", "-t 20:00"]
          env:
            OMP_NUM_THREADS: 2
            OMP_PROC_BIND: spread
            OMP_PLACES: threads
            OMP_DISPLAY_AFFINITY: true
            OMP_AFFINITY_FORMAT: '"host=%H, pid=%P, thread_num=%n, thread affinity=%A"'
          run: srun -n 8 -c 32 --cpu-bind=cores $_EXEC
      config:
        intel/19.0.3.199:
          module:
            load: [impi, intel/19.0.3.199] 
        intel/19.1.2.254:
          module:
            load: [impi, intel/19.1.2.254]       

  hybrid_mpi_hello_fortran_perlmutter:
    type: compiler
    executor: perlmutter.slurm.debug
    description: Hybrid MPI+OpenMP Hello World in Fortran on Perlmutter
    tags: [mpi, compile]
    source: src/hybrid-hello.f90
    compilers:
      name: ["gcc/11.2.0"]
      default:
        gcc:
          fc: ftn
          fflags: -openmp
          sbatch: ["-N 1", "-n 8", "-t 20:00", "-A m3503", "-C cpu"]
          env:
            OMP_NUM_THREADS: 8
            OMP_PROC_BIND: spread
            OMP_PLACES: threads
            OMP_DISPLAY_AFFINITY: true
            OMP_AFFINITY_FORMAT: '"host=%H, pid=%P, thread_num=%n, thread affinity=%A"'
          run: srun -n 8 --cpu-bind=cores $_EXEC
maintainers:
  - shahzebsiddiqui  
