version: "1.0"
buildspecs:
  laplace_mpi:
    type: compiler
    description: Laplace MPI code in C
    executor: slurm.knl_debug
    tags: ["mpi"]
    source: src/laplace_mpi.c
    compilers:
      name: ["^(intel/19.1.2.254)$"]
      default:
        all:
          sbatch: ["-N 1", "-n 4"]
          run: srun -n 4 $_EXEC
        intel:
          cc: mpiicc
          cflags: -O3
      config:
        intel/19.1.2.254:
          module:
            load: [impi/2020]
            swap: [intel, intel/19.1.2.254]
