buildspecs:
  laplace_mpi_perlmutter:
    type: compiler
    description: Laplace MPI code in C on Perlmutter
    executor: perlmutter.slurm.debug
    tags: [mpi, compile]
    source: src/laplace_mpi.c
    compilers:
      name: ["(cce)"]
      default:
        all:
          sbatch: ["-N 1", "-n 4", "-A m3503", "-t 5", "-C cpu"]
          run: srun -n 4 $_EXEC           
maintainers:
  - shahzebsiddiqui
