
buildspecs:
  laplace_mpi:
    type: compiler
    description: Laplace MPI code in C
    executor: perlmutter.slurm.debug
    tags: [mpi, compile]
    source: src/laplace_mpi.c
    compilers:
      name: ["^(cce\/13.0.1)", "^(cce\/13.0.2)"]
      default:
        all:
          sbatch: ["-N 1", "-n 4", "-A m3503", "-t 5", "-C cpu"]
          run: srun -n 4 $_EXEC
           
