version: "1.0"
buildspecs:
  hello_world_qthreads:
    type: compiler
    executor: local.e4s
    description: Hello World example using qthreads
    tags: ["e4s"]
    source: hello_world_multi.c
    compilers:
      name: ["^(intel/19.1.2.254)$"]
      default:
        intel:
          cflags: -L${QTHREADS_ROOT}/lib -I${QTHREADS_ROOT}/include
          ldflags: -lqthread
          pre_build: spackLoadUnique qthreads
      config:
        intel/19.1.2.254:
          module:
            swap: [intel, intel/19.1.2.254]
