version: "1.0"
buildspecs:
  moduletest_e4s_20_10:
    description: Run module load test for e4s 20.10 module tree
    type: script
    executor: cori.local.bash
    tags: [modules, e4s]
    run: MODULEPATH=/global/common/software/spackecp/e4s-20.10/modules/cray-cnl7-haswell/ python moduletest.py
    status:
      regex:
        stream: stdout
        exp: "PASS RATE: 100.000"

