buildspecs: 
  moduletest_e4s_22_02:
    description: Run module load test for e4s 22.02 module tree
    type: script
    executor: cori.local.bash
    tags: [modules, daily]
    run: MODULEPATH=/global/common/software/spackecp/cori/e4s-22.02/modules/cray-cnl7-haswell/ python moduletest.py
    status:
      regex:
        stream: stdout
        exp: "PASS RATE: 100.000"
