buildspecs:
  test_ml_command:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: Mimic ml command for some of the module commands 
    tags: [module]
    shell: bash -e
    run: |
      module -t list
      ml -t
      module -t av gcc
      ml -t av gcc
      module --raw show gcc
      ml --raw show gcc

  ml_load_unload_same_command:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: load and unload modules with ml in same command
    tags: [module]
    shell: bash -e
    run: |
      ml gcc
      ml
      ml -gcc craype
      ml
