buildspecs:
  module_version:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: check module version
    tags: [daily, system, module]
    run: module --version
    executors:
      perlmutter.local.bash:
        status:
          regex:
            stream: stderr
            exp: 'Modules based on Lua: Version 8\.7\.15'

maintainers:
  - "shahzebsiddiqui"
