#!/bin/bash

buildspecs:
  lmod_cmd:
    type: script
    executor: perlmutter.local.bash
    description: check for LMOD_CMD variable 
    tags: [module]
    shell: bash -e
    run: |
      echo $LMD_CMD
      $LMOD_CMD --version

  module_collection_list:
    type: script
    executor: perlmutter.local.bash
    description: show module collection list
    tags: [module]
    shell: bash -e
    run: module -t savelist

  module_and_ml_check:
    type: script
    executor: perlmutter.local.bash
    description: test module and ml command
    tags: [module]
    shell: bash -e
    run: |
      type module
      type ml
      module --version
      ml --version

  purge_restore:
    type: script
    executor: perlmutter.local.bash
    description: test module purge and restore. 
    tags: [module]
    shell: bash -e
    run: |
      module purge
      module restore
  module_test_shells:
    type: script
    executor: perlmutter.local.(bash|csh|zsh)
    description: test module command for bash, csh, zsh
    tags: [module]
    run: |
      module list


