
buildspecs:
  spider_check:
    skip: true
    type: script
    executor: perlmutter.local.bash
    description: Check LMOD spider utuility 
    tags: [module]
    run: |
      $LMOD_DIR/spider --version
      $LMOD_DIR/spider -o spider-json $MODULEPATH | jq .
      $LMOD_DIR/spider -o list $MODULEPATH
      $LMOD_DIR/spider -o softwarePage $MODULEPATH
