version: "1.0"
buildspecs:
  jobstats:
    type: script
    executor: cori.local.bash
    description: run jobstats program
    tags: ["system", "tool", "slurm"]
    run: |
      jobstats
      jobstats -j
      jobstats -u root

maintainers:
  - "@shahzebsiddiqui"
