buildspecs:
  showquota:
    type: script
    description: run the showquota utility
    executor: '(perlmutter|muller).local.bash'
    tags: [system]
    run: showquota
  showquota_check_m3503:
    type: script
    description: run the showquota check on m3503 project directory
    executor: '(perlmutter|muller).local.bash'
    tags: [system, e4s]
    run: showquota -N $CFS/m3503
  showquota_check_spackecp:
    type: script
    description: run showquota on /global/common/software/spackecp
    executor: '(perlmutter|muller).local.bash'
    tags: [system, e4s]
    run:  showquota -N /global/common/software/spackecp 
maintainers:
  - shahzebsiddiqui
