# https://gitlab.nersc.gov/nersc/consulting/reframe-at-nersc/reframe-nersc-tests/-/blob/main/filesystem_health/creates/src/creates_helper.sh
version: "1.0"
buildspecs:
  filesystem_benchmark_creates:
    description: "File System Health benchmark: Creates" 
    executor: cori.local.bash
    type: script
    tags: [filesystem, reframe, benchmark, hourly]
    vars:
      dirs: "(/global/cfs/cdirs/nstaff/ /global/common/software/nstaff/ $SCRATCH )"
      script: "$PWD/creates_helper.sh"
    run: | 
      for filesystem in "${dirs[@]}"; do
        cd $filesystem
        mkdir -p scratch
        cd scratch
        time -p $script
        cd $filesystem
      done
