
buildspecs:
  gpfs_clustername:
    type: script
    executor: cori.local.bash
    description: Get GPFS cluster name via mmlsconfig and check it is set to CORI.nersc.gov
    tags: ["daily", "system", "gpfs"]
    run: /usr/lpp/mmfs/bin/mmlsconfig clusterName
    status:
      regex:
        stream: stdout
        exp: "CORI.nersc.gov"

  ping_gpfs:
    type:  script
    executor: cori.local.bash
    description: ping gpfs cluster CORI.nersc.gov
    tags: ["daily", "system", "gpfs"]
    run: ping -c 4 -W 10 CORI.nersc.gov

  gpfs_check:
    type:  script
    executor: cori.local.bash
    description: query gpfs details
    tags: ["daily", "system", "gpfs"]
    run: |
      /usr/lpp/mmfs/bin/mmlsconfig
      /usr/lpp/mmfs/bin/mmlscluster
      /usr/lpp/mmfs/bin/mmlsmgr
      /usr/lpp/mmfs/bin/mmlsmount all

maintainers:
  - "shahzebsiddiqui"
