buildspecs:
  cuda_example_nvcc:
    type: script
    executor: '(perlmutter|muller).slurm.regular'
    description: Cuda C++ example using nvcc compiler
    sbatch: ["-N 1", "-C gpu", "-t 5", "-A m3503_g"]
    tags: [gpu]
    run: |
      ml PrgEnv-nvidia
      ml cudatoolkit
      make clean
      make
      ./vec_add
